### ISSUE TITLE
Add a help page and/or tooltips to the page

### ISSUE THREAD

**Issue by jameshiebert** [pacificclimate/weather-anomaly-tool#79]
I've been told by others that there are some subtleties to the weather anomaly viewer that make it challenging or confusing to use. Indeed, I myself had forgotten about what some of the various symbology on the map meant. We should write up a short HOWTO for people first coming to the tool.

**Comment by rod-glover** [comment]
The map itself could use a bit of an overhaul, too.

**Comment by rod-glover** [comment]
The app has had an overhaul, namely:
- Add colour bar
- Add info to station popup
- Improve selector layout

It's not clear what the "subtleties" referred to above are, but if it relates to difficulties interpreting the map marker colours (and distinguishing erroneous precip anomalies), then the current version should have reduced them considerably. That said, it is not a bad idea to have a brief in-app help/how-to page.
